spring:
  application:
    name: loan
  config:
    import: 
      - configserver:http://configserver-service:8071/
     # - configserver:http://localhost:8071/
  profiles:
    active:
      - dit

  cloud:
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication   
  rabbitmq:
    host: "rabbitmq-service"
    port: 5672
    username: "guest"
    password: "guest"
    
defaultBranchId: 1000