spring:
  application:
    name: bankly-loan-service
  config:
    import: 
      - configserver:http://configserver-service:8071/
     # - configserver:http://localhost:8071/
  profiles:
    active:
      - dit

    